### ISSUE TITLE
Blockchain data path

### ISSUE THREAD

**Issue by demicantrell** [ApolloFoundation/Apollo#1234]
Hello.

How can I correctly specify data dir path? I mean dir for blockchain files.

APPLICATION="path" in apl-common.sh it seems has no effect on blockchain files. This path uses only for jar files.

Thanks!

**Comment by 0486** [comment]
1) create directory conf in ~/.apl-blockchain/
2) create file apl-blockchain.properties (~/.apl-blockchain/conf/apl-blockchain.properties)
3) add parameter apl.customDbDir with database path
apl.customDbDir=/some/custom/path/here

**Comment by demicantrell** [comment]
> 1. create directory conf in ~/.apl-blockchain/
> 
>     2. create file apl-blockchain.properties (~/.apl-blockchain/conf/apl-blockchain.properties)
> 
>     3. add parameter apl.customDbDir with database path
>        apl.customDbDir=/some/custom/path/here

Thank you. Also I have found these keys in apl-exec*.jar --db-dir ./ --log-dir ./ --vault-key-dir ./ --config-dir ./
